name: your-nextjs-app
services:
  - name: web
    git:
      branch: main
      repo_clone_url: https://github.com/your-username/your-repo.git
    build_command: npm run build
    run_command: npm start
    environment_slug: node-js
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: NEXT_PUBLIC_API_URL
        value: ${NEXT_PUBLIC_API_URL}