name: your-nextjs-app
services:
  - name: web
    git:
      branch: develop
      repo_clone_url: https://github.com/vicesoftware/truck-scout.git
    build_command: npm run build
    run_command: npm start
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: NEXT_PUBLIC_API_URL
        value: ${NEXT_PUBLIC_API_URL}
    http_port: 3000
    routes:
    - path: /