version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: tms_test_db
      POSTGRES_USER: tms_test_user
      POSTGRES_PASSWORD: test_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tms_test_user -d tms_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://tms_test_user:test_password@postgres:5432/tms_test_db
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      target: test-runner
    environment:
      API_URL: http://nextjs:3000
      DATABASE_URL: postgresql://tms_test_user:test_password@postgres:5432/tms_test_db
      TEST_MODE: ${TEST_MODE:-watch}
      JEST_WORKERS: ${JEST_WORKERS:-50%}
      NODE_OPTIONS: "--max-old-space-size=4096"
    volumes:
      - ./prisma:/app/prisma
      - ./src:/app/src
      - ./test:/app/test
      - ./scripts:/app/scripts
    depends_on:
      nextjs:
        condition: service_healthy
    command: >
      sh -c "
        ENVIRONMENT=test DATABASE_URL=postgresql://tms_test_user:test_password@postgres:5432/tms_test_db \
        sh scripts/deploy-migrations.sh && \
        npm run test:api:${TEST_MODE:-watch}
      "

volumes:
  postgres_data:
