services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: tms_test_db
      POSTGRES_USER: tms_test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - test_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tms_test_user -d tms_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test_pgdata:
