version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: tms_test_db
      POSTGRES_USER: tms_user
      POSTGRES_PASSWORD: secure_password_here
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: super_secret
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:  
  pgadmin_data:
