# Base stage
FROM node:20-alpine as base
WORKDIR /app

# First copy only package files to leverage Docker cache for dependencies
COPY package*.json ./
RUN npm ci --only=production

# Then copy the rest of the application files
COPY . .

# Development dependencies stage
FROM base as dev-deps
RUN npm ci

# Test stage
FROM dev-deps as test
ENV NODE_ENV=test
ENV ENVIRONMENT=test

# Run tests
CMD ["npm", "run", "test"]
