name: Deploy to Development Environment

on:
  push:
    branches:
      - develop
    paths:
      - 'prisma/schema.prisma'
      - 'prisma/migrations/**'
      - '.github/workflows/deploy-dev.yml'

jobs:
  deploy-migrations:
    name: Deploy Database Migrations
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install doctl to connect to Digital Ocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Reset Database and Run Migrations
        run: |
          echo "Resetting database, applying migrations, and seeding data..."
          npx prisma migrate reset --force

      - name: Verify Migration Status
        run: |
          echo "Verifying migration status..."
          npx prisma migrate status
